# Generated by Django 4.2 on 2026-04-24 14:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('classification', 'Dispute Classification'), ('evidence_guidance', 'Evidence Guidance'), ('document_processing', 'Document Processing'), ('timeline', 'Timeline Construction'), ('case_packet', 'Case Packet Generation')], max_length=50)),
                ('prompt_hash', models.CharField(max_length=64)),
                ('model_response', models.TextField()),
                ('retrieved_chunks', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('full_prompt', models.TextField(blank=True)),
                ('model_name', models.CharField(default='gpt-4o', max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('chunk_similarity_scores', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispute_type', models.CharField(choices=[('TENANT_LANDLORD', 'Tenant-Landlord Dispute'), ('FREELANCE_PAYMENT', 'Freelance/Contract Payment Dispute')], max_length=50)),
                ('dispute_stage', models.CharField(blank=True, max_length=50)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('gap_report', models.JSONField(blank=True, null=True)),
                ('classification_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('user_narrative', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('classification_error', 'Classification Error'), ('missing_evidence', 'Missing Evidence Item'), ('incorrect_timeline', 'Incorrect Timeline'), ('hallucination', 'Hallucinated Content'), ('other', 'Other')], max_length=50)),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.ailog')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JurisdictionMapping',
            fields=[
                ('mapping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispute_type', models.CharField(max_length=50)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('applicable_laws', models.JSONField()),
            ],
            options={
                'db_table': 'jurisdiction_mappings',
                'unique_together': {('dispute_type', 'jurisdiction')},
            },
        ),
        migrations.CreateModel(
            name='EvidenceTemplate',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispute_type', models.CharField(max_length=50)),
                ('evidence_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('supportive', 'Supportive'), ('optional', 'Optional')], max_length=20)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'evidence_templates',
                'ordering': ['dispute_type', 'display_order'],
                'unique_together': {('dispute_type', 'evidence_name')},
            },
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('evidence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('extracted_text', models.TextField(blank=True)),
                ('classification_tag', models.CharField(choices=[('CONTRACT', 'Contract'), ('RECEIPT', 'Receipt'), ('COMMUNICATION', 'Communication'), ('PHOTOGRAPH', 'Photograph'), ('LEGAL_NOTICE', 'Legal Notice'), ('OTHER', 'Other')], default='OTHER', max_length=100)),
                ('completeness_flag', models.BooleanField(default=False)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('extracted_entities', models.JSONField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='cases.case')),
            ],
            options={
                'db_table': 'evidence_items',
                'ordering': ['upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('actors', models.JSONField(default=list)),
                ('action_description', models.TextField()),
                ('evidence_refs', models.JSONField(default=list)),
                ('legal_relevance_tag', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(choices=[('auto_extracted', 'Auto-Extracted from Evidence'), ('manual_entry', 'Manual User Entry')], default='auto_extracted', max_length=20)),
                ('is_merged', models.BooleanField(default=False)),
                ('merged_from_event_ids', models.JSONField(default=list)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['event_date', 'event_id'],
            },
        ),
        migrations.CreateModel(
            name='CasePacket',
            fields=[
                ('packet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executive_summary', models.TextField()),
                ('issues', models.JSONField()),
                ('evidence_table', models.JSONField()),
                ('timeline', models.JSONField()),
                ('gap_report', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer_questions', models.JSONField(default=list)),
                ('pdf_file_path', models.CharField(blank=True, max_length=500)),
                ('regeneration_count', models.IntegerField(default=0)),
                ('last_regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_packet', to='cases.case')),
            ],
            options={
                'db_table': 'case_packets',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='ailog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='cases.case'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['case', 'classification_tag'], name='evidence_it_case_id_7faad3_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['processing_status'], name='evidence_it_process_b10135_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['case', 'event_date'], name='events_case_id_cdbc5b_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['user', 'status'], name='cases_user_id_c07d24_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['dispute_type'], name='cases_dispute_310265_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_at'], name='cases_created_6583ad_idx'),
        ),
        migrations.AddIndex(
            model_name='ailog',
            index=models.Index(fields=['case', 'module'], name='ai_logs_case_id_79db5b_idx'),
        ),
        migrations.AddIndex(
            model_name='ailog',
            index=models.Index(fields=['timestamp'], name='ai_logs_timesta_d05607_idx'),
        ),
        migrations.AddIndex(
            model_name='ailog',
            index=models.Index(fields=['prompt_hash'], name='ai_logs_prompt__95c7bb_idx'),
        ),
    ]
